package com.codifica.chatbot.core.domain.chat;

// TODO: Implementar enum substituindo strings
public enum ChatStep {
    INICIO,

    // CADASTRO CLIENTE
    AGUARDANDO_NOME_CLIENTE,
    AGUARDANDO_TELEFONE_CLIENTE,
    AGUARDANDO_CEP_CLIENTE,
    AGUARDANDO_NUMERO_ENDERECO_CLIENTE,
    AGUARDANDO_COMPLEMENTO_CLIENTE,
    AGUARDANDO_RESPOSTA_CADASTRO_CLIENTE,

    // CADASTRO PET
    AGUARDANDO_CADASTRO_PET,
    AGUARDANDO_NOME_PET,
    AGUARDANDO_RACA_PET,
    AGUARDANDO_RESPOSTA_CADASTRO_PET,

    // SOLICITACAO
    AGUARDANDO_AGENDAMENTO,
    AGUARDANDO_ESCOLHA_PET,
    AGUARDANDO_ESCOLHA_DIA,
    AGUARDANDO_ESCOLHA_HORARIO,
    AGUARDANDO_ESCOLHA_SERVICOS,
    AGUARDANDO_ORCAMENTO,
    ACEITO_PELO_USUARIO,
    AGUARDANDO_CONFIRMACAO_CLIENTE,
    AGUARDANDO_RESPOSTA_SOLICITACAO_ACEITA,
    AGENDAMENTO_CONFIRMADO,
    FIM,
    ERRO,
    ERRO_CADASTRO_CLIENTE,
    ERRO_CADASTRO_PET,
    ERRO_CADASTRO_SOLICITACAO
}
